title: DigiPres Learning Resources
description: Learning resources site
url: "/learning/"
editor_url: https://digipres-org-learning.netlify.app

show_edit_site_warning: true

markdown: kramdown

# markdown: CommonMarkGhPages
#commonmark:
#  options: ["FOOTNOTES"]
#  extensions: ["strikethrough", "autolink", "table"]

# Using Jekyll Collections to manage the contents in an idiomatic way:
# See https://jekyllrb.com/docs/collections/
collections:
  resources:
    output: true
  skills:
    output: true
  roles:
    output: true

# Set defaults for some properties:
# See https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  - scope:
      path: "" # empty string for all files
    values:
      layout: "default"
  - scope:
      path: ""
      type: resources # Using the collections name to do the mapping
    values:
      layout: "resource"

navigation:
- text: Resources
  url: /resources/
- text: Skills
  url: /skills/
- text: Roles
  url: /roles/


# Manage includes/excludes:
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
 - _pagefind

#theme: jekyll-theme-bootstrap5
paginate: 3
plugins:
  - jekyll-feed
  - jekyll-paginate
