---
title: DigiPres Learning Resources
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  resources:
    title: Resources
    output: true
  roles:
    title: Roles
    output: true
  skills:
    title: Skills
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: resources
  values:
    layout: resource
- scope:
    path: ''
    type: skills
  values:
    layout: skills
- scope:
    path: ''
    type: roles
  values:
    layout: roles
description: Learning resources site
editor_url: https://digipres-learning-resources.netlify.app/
editable: false
baseurl: "/learning/"
markdown: kramdown
navigation:
- text: Resources
  url: "/resources/"
- text: Skills
  url: "/skills/"
- text: Roles
  url: "/roles/"
- text: Search
  url: "/search/"
exclude:
- Gemfile
- Gemfile.lock
- README.md
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
include:
- _pagefind
feed:
  collections:
    resources:
      path: "/resources/feed.xml"
paginate: 3
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-last-modified-at
