# config.yml
# ----------
# See here for documentation:
#   https://decapcms.org/docs/configuration-options/
#

# How to talk to the Git datafile store:
backend:
  name: github
  repo: Digital-Preservation-Coalition/learning
  branch: main

# Where in the repository to store uploaded files (may be overridden for specific collection/fields below):
media_folder: "assets/uploads"

# Use the PR-based editorial workflow:
publish_mode: editorial_workflow

# Path where the site is hosted:
# Not needed at present.
#site_url: /learning/

# Defining the different collections of items:
collections:

- name: resources
  label: Learning Resources
  label_singular: 'Learning Resource'
  folder: _resources
  create: true
  path: '{{slug}}/index'
  media_folder: ''
  public_folder: ''
  fields:
  - label: "Resource Name"
    name: title
    widget: string
    required: true
    hint: "The name of the resource."
  - label: Link
    name: resource_url
    widget: string
    required: true
    hint: "A hyperlink to more information about the resource."
  - label: "Type of Resource"
    name: resource-type
    widget: "select"
    options: [
      "Article",
      "Book/eBook",
      "Conference",
      "Conference Proceedings",
      "Degree Program",
      "Event Recording",
      "Group/Network",
      "In Person Training",
      "Journal",
      "Knowledge Base",
      "Mailing List",
      "Online Training - Instructor Led",
      "Online Training - Self Directed",
      "Report",
      "Scholarship/Grant",
      "Toolkit",
      "Training Content" 
    ]
    required: true
    hint: "What type of resource is being described."
  - label: "Provider"
    name: provider
    widget: string
    required: true
    hint: "Name of the organization or individual who provides the course."
  - label: "Creator(s)"
    name: creators
    widget: list
    required: false
    fields:
    - { label: "Creator", name: creator, widget: string, required: false }
    hint: "Name(s) of the organizations and/or individuals who created the resource."
  - label: "Release Year"
    name: release-year
    widget: "number"
    value_type: "int"
    min: 1900
    required: false
    hint: "Year the resource was released/published."
  - label: "Description"
    name: "body"
    widget: "markdown"
    required: true
    hint: "A short text description of resource."
  - label: "Learning Objectives"
    name: learning-objectives
    widget: list
    required: false
    fields:
    - { label: "Learning Objective", name: learning-objective, widget: string, required: false }
    hint: "A list of learning objectives related to the resource."
  - label: "Related Skills"
    label_singular: "Skill"
    name: skill-levels
    widget: list
    # There must be at least one entry for skill level:
    min: 1
    max: 10
    # Show skill and level in collapsed view of each entry:
    summary: '{{fields.skill}} - level {{fields.level}}'
    fields:
        - { label: "Skill", name: "skill", widget: "relation", collection: "skills", search_fields: ["title"], value_field: "title", display_fields: ["title"], options_length: 100 }
        - label: "Level"
          name: "level"
          widget: "select"
          options:
          - { label: "0. Novice", value: "0" }
          - { label: "1. Beginner", value: "1" }
          - { label: "2. Intermediate", value: "2" }
          - { label: "3. Advanced", value: "3" }
          - { label: "4. Expert", value: "4" }
    hint: "A related skill element and level from the [DPC DP Competency Framework](https://www.dpconline.org/digipres/prof-development/dp-competency)."
  - label: "Related Roles"
    label_singular: "Related Role"
    name: roles
    widget: list
    fields:
        - { label: "Role", name: "role", widget: "relation", collection: "roles", search_fields: ["title"], value_field: "title", display_fields: ["title"] }
    hint: "Specific roles for whom this resource might be useful."
  - label: "Country"
    name: country
    widget: select
    options: [
      "Afghanistan",
      "Albania",
      "Algeria",
      "Andorra",
      "Angola",
      "Antigua and Barbuda",
      "Argentina",
      "Armenia",
      "Australia",
      "Austria",
      "Azerbaijan",
      "The Bahamas",
      "Bahrain",
      "Bangladesh",
      "Barbados",
      "Belarus",
      "Belgium",
      "Belize",
      "Benin",
      "Bhutan",
      "Bolivia",
      "Bosnia and Herzegovina",
      "Botswana",
      "Brazil",
      "Brunei",
      "Bulgaria",
      "Burkina Faso",
      "Burundi",
      "Cabo Verde",
      "Cambodia",
      "Cameroon",
      "Canada",
      "Central African Republic",
      "Chad",
      "Chile",
      "China",
      "Colombia",
      "Comoros",
      "Congo, Democratic Republic of the",
      "Congo, Republic of the",
      "Costa Rica",
      "Côte d’Ivoire",
      "Croatia",
      "Cuba",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Djibouti",
      "Dominica",
      "Dominican Republic",
      "East Timor (Timor-Leste)",
      "Ecuador",
      "Egypt",
      "El Salvador",
      "Equatorial Guinea",
      "Eritrea",
      "Estonia",
      "Eswatini",
      "Ethiopia",
      "Fiji",
      "Finland",
      "France",
      "Gabon",
      "The Gambia",
      "Georgia",
      "Germany",
      "Ghana",
      "Greece",
      "Grenada",
      "Guatemala",
      "Guinea",
      "Guinea-Bissau",
      "Guyana",
      "Haiti",
      "Honduras",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Ireland",
      "Israel",
      "Italy",
      "Jamaica",
      "Japan",
      "Jordan",
      "Kazakhstan",
      "Kenya",
      "Kiribati",
      "Korea, North",
      "Korea, South",
      "Kosovo",
      "Kuwait",
      "Kyrgyzstan",
      "Laos",
      "Latvia",
      "Lebanon",
      "Lesotho",
      "Liberia",
      "Libya",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Madagascar",
      "Malawi",
      "Malaysia",
      "Maldives",
      "Mali",
      "Malta",
      "Marshall Islands",
      "Mauritania",
      "Mauritius",
      "Mexico",
      "Micronesia, Federated States of",
      "Moldova",
      "Monaco",
      "Mongolia",
      "Montenegro",
      "Morocco",
      "Mozambique",
      "Myanmar (Burma)",
      "Namibia",
      "Nauru",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Nicaragua",
      "Niger",
      "Nigeria",
      "North Macedonia",
      "Norway",
      "Oman",
      "Pakistan",
      "Palau",
      "Palestine",
      "Panama",
      "Papua New Guinea",
      "Paraguay",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Qatar",
      "Romania",
      "Russia",
      "Rwanda",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Vincent and the Grenadines",
      "Samoa",
      "San Marino",
      "Sao Tome and Principe",
      "Saudi Arabia",
      "Senegal",
      "Serbia",
      "Seychelles",
      "Sierra Leone",
      "Singapore",
      "Slovakia",
      "Slovenia",
      "Solomon Islands",
      "Somalia",
      "South Africa",
      "Spain",
      "Sri Lanka",
      "Sudan",
      "Sudan, South",
      "Suriname",
      "Sweden",
      "Switzerland",
      "Syria",
      "Taiwan",
      "Tajikistan",
      "Tanzania",
      "Thailand",
      "Togo",
      "Tonga",
      "Trinidad and Tobago",
      "Tunisia",
      "Turkey",
      "Turkmenistan",
      "Tuvalu",
      "Uganda",
      "Ukraine",
      "United Arab Emirates",
      "United Kingdom",
      "United States",
      "Uruguay",
      "Uzbekistan",
      "Vanuatu",
      "Vatican City",
      "Venezuela",
      "Vietnam",
      "Yemen",
      "Zambia",
      "Zimbabwe"
    ]
    required: false
    hint: "Country where this resource was produced/released."
  - label: "Language"
    name: language
    widget: string
    required: false
    hint: "The language the resource is presented in."
  - label: "Free or Paid"
    name: free-or-paid
    widget: select
    options: [
      "Free",
      "Paid"
    ]
    required: true
    hint: "Is the resource available to access for free or does in need to be paid for?"
  - label: "Cost"
    name: cost
    widget: string
    required: false
    hint: "If paid, how much does it cost to access the resource?"
  - label: "Qualifications"
    name: qualifications
    widget: string
    required: false
    hint: "Description of any qualification or credits gained upon completion."
  - label: "Open Access"
    name: open-access
    widget: select
    options: [
      "Yes",
      "No",
      "Unsure"
    ]
    required: false
    hint: "Is the resource available for reuse under an open license?"
  - label: "Licence"
    name: licence
    widget: string
    required: false
    hint: "License the resource is released under (if specified)."
  - label: "Part of Series"
    name: series
    widget: string
    required: false
    hint: "Information on if this resource is part of a series."
  - label: "Related Resources"
    label_singular: "Related Resource"
    name: related-items
    widget: list
    fields:
        - { label: "Resource", name: "resource", widget: "relation", collection: "resources", search_fields: ["title"], value_field: "title", display_fields: ["title"] }
    required: false
    hint: "Links to information on related resources."
  - label: "Resource Materials"
    name: files
    widget: file
    required: false
    media_library:
      config:
        multiple: true
    hint: "Content relating to the resource (e.g. training presentations, worksheets, reading lists etc.)."
  - label: "Logo"
    name: "logo"
    widget: "image"
    required: false
  - label: "Entry Created"
    name: "created"
    widget: "datetime"
    date_format: "YYYY-MM-DD"
    hint: "Date this entry was created."
  - label: "Entry Updated"
    name: "updated"
    widget: "datetime"
    date_format: "YYYY-MM-DD"
    hint: "Date this entry was last updated."

- name: skills
  label: Skills
  label_singular: Skill
  folder: _skills
  create: false
  delete: false
  hide: true
  fields:
  - label: Title
    name: title
    widget: string
  - label: "Competency Area"
    name: "competency-area"
    widget: "select"
    options: [
      "Governance, Resourcing, and Management", 
      "Communications and Advocacy", 
      "Information Technology", 
      "Legal and Social Responsibilities", 
      "Digital Preservation Domain Specific"
    ]
  - label: "Description"
    name: "body"
    widget: "markdown"
    required: false

- name: roles
  label: Roles
  label_singular: Role
  folder: _roles
  create: false
  delete: false
  hide: true
  fields:
  - label: Name
    name: title
    widget: string
  - label: "Description"
    name: "body"
    widget: "markdown" 
    required: false
  - label: "Alternative Names"
    name: alternative-names
    widget: list
    fields:
    - { label: Name, name: name, widget: string }

- name: 'pages'
  label: 'Other Pages'
  editor:
    preview: false
  files:
    - label: 'Homepage'
      name: 'index'
      file: 'index.md'
      preview_path: /
      fields:
        - { label: 'Title', name: 'title', widget: 'string', default: 'Welcome' }
        - { label: 'Body', name: 'body', widget: 'markdown' }
