# config.yml

backend:
  #name: git-gateway
  name: github
  repo: digipres/learning
  branch: main
media_folder: "assets/uploads"

# Use the PR-based editorial workflow:
#publish_mode: editorial_workflow

#site_url: /learning/

collections:

- name: resources
  label: Learning Resources
  label_singular: 'Learning Resource'
  folder: _resources
  create: true
  path: '{{slug}}/index'
  media_folder: ''
  public_folder: ''
  fields:
  - { label: "Name", name: title, widget: string }
  - { label: "Description", name: "body", widget: "markdown", required: false }
  - { label: "Logo", name: "logo", widget: "image", required: false }
  - { label: URL, name: resource_url, widget: string }
  - label: "Skills"
    label_singular: "Skill"
    name: skill-levels
    widget: list
    # There must be at least one entry for skill level:
    min: 1
    max: 10
    # Show skill and level in collapsed view of each entry:
    summary: '{{fields.skill}} - level {{fields.level}}'
    fields:
        - { label: "Skill", name: "skill", widget: "relation", collection: "skills", search_fields: ["title"], value_field: "title", display_fields: ["title"] }
        - label: "Level"
          name: "level"
          widget: "select"
          options:
          - { label: "0. Novice", value: "0" }
          - { label: "1. Beginner", value: "1" }
          - { label: "2. Intermediate", value: "2" }
          - { label: "3. Advanced", value: "3" }
          - { label: "4. Expert", value: "4" }
  - label: "Roles"
    label_singular: "Role"
    name: roles
    widget: list
    fields:
        - { label: "Role", name: "role", widget: "relation", collection: "roles", search_fields: ["title"], value_field: "title", display_fields: ["title"] }
  - { label: "Learning Objectives", name: learning-objectives, widget: list, allow_add: true, required: false }
  - { label: "Cost", name: cost, widget: string, required: false }
  - { label: "Language", name: language, widget: string, required: false }
  - { label: "Creators", name: creators, widget: list, allow_add: true, required: false }
  - { label: "Provider", name: provider, widget: string, required: false }
  - { label: "Licence", name: licence, widget: string, required: false }
  - { label: "Resource Type", name: resource-type, widget: string, required: false }
  - { label: "Accredited", name: accredited, widget: string, required: false }
  - { label: "Open Access", name: open-access, widget: boolean, required: false }
  - { label: "Series", name: series, widget: string, required: false }
  - label: files
    name: files
    widget: file
    required: false
    media_library:
      config:
        multiple: true
  - label: "Related Items"
    label_singular: "Related Item"
    name: related-items
    widget: list
    fields:
        - { label: "Resource", name: "resource", widget: "relation", collection: "resources", search_fields: ["title"], value_field: "title", display_fields: ["title"] }
  - label: "Resource record created on"
    name: "created"
    widget: "datetime"
    date_format: "YYYY-MM-DD"

- name: skills
  label: Skills
  label_singular: Skill
  folder: _skills
  create: true
  fields:
  - { label: Title, name: title, widget: string }
  - label: "Competency Area"
    name: "competency-area"
    widget: "select"
    options: [
      "Governance, Resourcing, and Management", 
      "Communications and Advocacy", 
      "Information Technology", 
      "Legal and Social Responsibilities", 
      "Digital Preservation Domain Specific"
    ]
  - { label: "Body", name: "body", widget: "markdown", required: false }

- name: roles
  label: Roles
  label_singular: Role
  folder: _roles
  create: true
  fields:
  - { label: Name, name: title, widget: string }
  - { label: "Description", name: "body", widget: "markdown", required: false }
  - label: "Alternative Names"
    name: alternative-names
    widget: list
    fields:
    - { label: Name, name: name, widget: string }

- name: 'pages'
  label: 'Other Pages'
  editor:
    preview: false
  files:
    - label: 'Homepage'
      name: 'index'
      file: 'index.md'
      preview_path: /
      fields:
        - { label: 'Title', name: 'title', widget: 'string', default: 'Welcome' }
        - { label: 'Body', name: 'body', widget: 'markdown' }
