# config.yml

backend:
  #name: git-gateway
  name: github
  repo: digipres/learning
  branch: main
media_folder: "assets/uploads"

# Use the PR-based editorial workflow:
publish_mode: editorial_workflow

#site_url: https://www.digipres.org/learning/

collections:

- name: items
  label: Learning Resources
  label_singular: 'Learning Resource'
  folder: items
  create: true
  path: '{{slug}}/index'
  media_folder: ''
  public_folder: ''
  fields:
  - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'item' }
  - { label: Title, name: title, widget: string }
  - { label: "Logo", name: "logo", widget: "image", required: false }
  - { label: URL, name: url, widget: string }
  - label: "Skills"
    label_singular: "Skill"
    name: skill-levels
    widget: list
    # There must be at least one entry for skill level:
    min: 1
    max: 10
    # Show skill and level in collapsed view of each entry:
    summary: '{{fields.skill}} - level {{fields.level}}'
    fields:
        - {label: "Skill", name: "skill", widget: "relation", collection: "skills", search_fields: ["title"], value_field: "title", display_fields: ["title"] }
        - label: "Level"
          name: "level"
          widget: "select"
          options:
          - { label: "0. Novice", value: "0" }
          - { label: "1. Beginner", value: "1" }
          - { label: "2. Intermediate", value: "2" }
          - { label: "3. Advanced", value: "3" }
          - { label: "4. Expert", value: "4" }
  - label: "Roles"
    label_singular: "Role"
    name: roles
    widget: list
    fields:
        - {label: "Role", name: "role", widget: "relation", collection: "roles", search_fields: ["title"], value_field: "title", display_fields: ["title"] }
  - { label: "Body", name: "body", widget: "markdown", required: false }
  - label: files
    name: files
    widget: file
    required: false
    media_library:
      config:
        multiple: true

- name: skills
  label: Skills
  label_singular: Skill
  folder: skills
  create: true
  fields:
  - { label: Title, name: title, widget: string }
  - {label: "Competency Area", name: "competency-area", widget: "select", options: ["Governance, Resourcing, and Management", "Communications and Advocacy", "Information Technology", "Legal and Social Responsibilities", "Digital Preservation Domain Specific"] }
  - { label: "Body", name: "body", widget: "markdown", required: false }

- name: roles
  label: Roles
  label_singular: Role
  folder: roles
  create: true
  fields:
  - { label: Name, name: title, widget: string }
  - { label: "Description", name: "body", widget: "markdown", required: false }
  - label: "Alternative Names"
    name: alternative-names
    widget: list
    fields:
    - { label: Name, name: name, widget: string }

- name: 'pages'
  label: 'Other Pages'
  editor:
    preview: false
  files:
    - label: 'Homepage'
      name: 'index'
      file: 'index.md'
      preview_path: /
      fields:
        - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'home' }
        - { label: 'Title', name: 'title', widget: 'string', default: 'Welcome' }
        - { label: 'Body', name: 'body', widget: 'markdown' }
