# config.yml

backend:
  #name: git-gateway
  name: github
  repo: digipres/learning
  branch: main
media_folder: "assets/uploads"

# Use the PR-based editorial workflow:
publish_mode: editorial_workflow

#site_url: https://www.digipres.org/learning/

collections:

- name: items
  label: Learning Resources
  label_singular: 'Learning Resource'
  folder: items
  fields:
  - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'item' }
  - { label: Title, name: title, widget: string }
  - { label: "Logo", name: "logo", widget: "image", media_folder: "images", required: false }
  - { label: URL, name: url, widget: string }
  - label: "Skills"
    name: skill-levels
    widget: list
    fields:
        - {label: "Skill", name: "skill", widget: "relation", collection: "skills", search_fields: ["title"], value_field: "title", display_fields: ["title"] }
        - {label: "Level", name: "level", widget: "select", options: ["0", "1", "2", "3", "4"] }
  - { label: "Body", name: "body", widget: "markdown", required: false }

- name: skills
  label: Skills
  label_singular: Skill
  folder: skills
  fields:
  - { label: Title, name: title, widget: string }
  - {label: "Competency Area", name: "competency-area", widget: "select", options: ["Governance, Resourcing, and Management", "Communications and Advocacy", "Information Technology", "Legal and Social Responsibilities", "Digital Preservation Domain Specific"] }
  - { label: "Body", name: "body", widget: "markdown", required: false }

- name: 'pages'
  label: 'Other Pages'
  editor:
    preview: false
  files:
    - label: 'Homepage'
      name: 'index'
      file: 'index.md'
      preview_path: /
      fields:
        - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
        - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'home' }
        - { label: 'Body', name: 'body', widget: 'markdown' }
